server:
  port: 9093  # should be same with servicecomb.rest.address to use web container
  servlet:
    context-path: /provider
  tomcat:
    accesslog:
      enabled: true
      directory: /Users/castile/Documents/Code/servicecomb-samples/basic/provider/access/
      pattern: '"[%{x-biz-tenantId}r]" %h %l %u %t "%r" %s %b %Dms "%{Referer}i" "%{User-Agent}i" "%{X-Request-ID}i" "%{X-Forwarded-For}i"'
# override common configurations in common module
servicecomb-config-order: 10

servicecomb:
  server:
    context:
      ## 开启支持在将上下文传递到cse请求中
      pass: true
  accesslog:
    ## server 端 启用access log
    enabled: true
    ##  server 端 自定义 access log 日志格式
    pattern: "[%{x-biz-tenantId}i]-%h - - %t %r %s %B %D"
    request:
      ## client 端开启 request log
      enabled: true
      ## client 端自定义 request log 日志格式
      pattern: "%h %SCB-transport - - %t %r %s %D"
  service:
    application: basic-application
    name: provider
    version: 0.0.1
    registry:
      # Default using local service center
      address: http://localhost:30100
      # address: https://cse.cn-south-1.myhuaweicloud.com
      instance:
        watch: false
  kie:
    serverUri: http://localhost:30110

  rest:
    address: 0.0.0.0:9093 # should be same with server.port to use web container
    servlet:
      # https://servicecomb.apache.org/references/java-chassis/2.x/zh_CN/featured-topics/application-porter/porter-website.html#tomcatspring-bootweb
      urlPattern: /cse/*

  handler:
    chain:
      Consumer:
        default: context, qps-flowcontrol-consumer, loadbalance
      Provider:
        default: context, qps-flowcontrol-provider
# Configure AK/SK credentials if needed. Default not enabled.
#  credentials:
#    akskEnabled: false
#    accessKey: add your ak/sk from huaweicloud
#    secretKey: add your ak/sk from huaweicloud
#    akskCustomCipher: default
management:
  endpoint:
    health:
      show-details: ALWAYS
#    project: cn-south-1